export { default as numericalIcon } from "./numerical.png"
export { default as oopIcon } from "./oop project.png"
export { default as parabounceIcon } from "./parabounce.png"
export { default as readifyIcon } from "./readifylogo.png"
export { default as cinemaIcon } from "./cinema_paradiso.png"
export { default as parabounceLogo } from "./paraBounceLogo.png"
export { default as policeIcon } from "./policeLogo.png"
export { default as readifyLogo } from "./readifyappLogo.png"
export { default as cinemaHomepage } from "./homepage.png"
export { default as numericalLogo } from "./numericalIcon.png"
export { default as movieLogo } from "./movieDatabase.png"
