export { default as parabounceIcon } from "./parabounce.png"
export { default as readifyIcon } from "./readifylogo.png"
export { default as cinemaIcon } from "./cinema_paradiso.png"
export { default as parabounceLogo } from "./paraBounceLogo.png"
export { default as readifyLogo } from "./readifyappLogo.png"
export { default as cinemaHomepage } from "./homepage.png"

// Project banners and logos
export { default as agrisenseBanner } from "./greenleaf.jpeg"
export { default as agrisenseLogo } from "./greenleaf-logo.png"
export { default as signolightBanner } from "./signolight.png"
export { default as signolightLogo } from "./signolight-logo.png"
export { default as whatsappSummarizerBanner } from "./wp-summaizer.png"
export { default as whatsappSummarizerLogo } from "./wp-summarizer-logo.png"
export { default as slidecommanderBanner } from "./slide-commander.png"
export { default as slidecommanderLogo } from "./slide-commander-logo.png"
export { default as murderInKuetBanner } from "./murder-in-kuet.png"
export { default as murderInKuetLogo } from "./murder-in-kuet-logo.png"
export { default as smartCarBanner } from "./smart-car.jpeg"
export { default as smartCarLogo } from "./smart-car-logo.png"
